### ISSUE TITLE
classname is always Minitest::Result on newer versions of minitest

### ISSUE THREAD

**Issue by fsateler** [aespinosa/minitest-junit#4]
First of all, thanks for this awesome gem!

I believe this is because starting with 5.11, [minitest wraps the results in a Result class](https://github.com/seattlerb/minitest/commit/00433fc0a4fdd0e6b302aace633384ba13122376), and so the report always contains `Minitest::Result` in the `classname` attribute.

I have worked around this locally by changing `format_class` to use this new field:

```ruby
Minitest::Junit::Reporter.class_eval do
  def format_class(result)
    if @options[:junit_jenkins]
      result.klass.to_s.gsub(/(.*)::(.*)/, '\1.\2')
    else
      result.klass
    end
  end
end
```

I was going to post a PR but that would require bumping the minitest dependency. What do you think? Bump the dependency, or have an `if result.respond_to?(:klass)`?

**Comment by aespinosa** [comment]
https://github.com/minitest/minitest/commit/00433fc0a4fdd0e6b302aace633384ba13122376#diff-b43f1192f616004aa819abdb67ebe90528572c49ec805b9ad66ce45e1afce97bR453 shouldn't seem to say so.

can you give an example unit test that illustrates the problem?

**Comment by fsateler** [comment]
This exhibits the problem:

```ruby
# thetest.rb
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "minitest", "= 5.14.4"
  gem "minitest-junit"
end

require "minitest/autorun"

class BugTest < Minitest::Test
  def test_stuff
    assert true
  end
end
```

And run it:

```
% ruby thetest.rb --junit --junit-filename=/dev/stdout
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Using bundler 2.1.4
Using minitest 5.14.4
Using builder 3.2.4
Using minitest-junit 0.3.0
Run options: --junit --junit-filename=/dev/stdout --seed 63401

# Running:

.

Finished in 0.001296s, 771.7151 runs/s, 771.7151 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
<testsuite>
<testcase classname="Minitest::Result" name="test_stuff" time="1.9975006580352783e-05" assertions="1"></testcase>
</testsuite>
```

See how the `classname` is `Minitest::Result` instead of `BugTest`

**Comment by aespinosa** [comment]
thanks. i was able to reproduce the issue and validated the original fix you posted earlier.  My plan is to

(1) cut 0.4.0 pinning minitest to ~> 5.0 && < 5.11
(2) cut 1.0.0 with the above fix (and bump the minitest requirement)
